spring:
  application:
    name: zuul-server
server:
  port: 8001
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost
    preferIpAddress: true
zuul:
  routes:
    user-service:
      path: /user/**
      serviceId: user-microservice
      stripPrefix: true