spring:
  application:
    name: user-microservice
  datasource:
    url: jdbc:h2:file:~/demodb
server:
  port: 8002
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    preferIpAddress: true

